### PR TITLE
Fix code running spinner is not sheet dependent

### LINKED ISSUE #1306: Cell running spinner isn't sheet dependent
Bleeds over across all sheets where you can see the spinner in the cell that is spinning in any other sheet. 

E.g. if in sheet 1 I'm running code and there's a spinner, in sheet 2 in that same cell location I'll be able to see the spinner from sheet 1 bled into my sheet 2. 

See Slack for repro file

### PR DESCRIPTION
**Pull request by davidfig**
Fixes #1306

### CODE REVIEW

File: quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx [hunk 1]
```diff
@@ -109,16 +109,30 @@ export const CodeRunning = () => {
     };
   }, [playerCode?.length]);
 
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  const [_, setTrigger] = useState(0);
```
Comment (ddimaria) [inline quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx:113]: It's silly that TS requires a disable line for this.
