### PR TITLE
fix: close editor when creating new file

### LINKED ISSUE #462: bug: create new file from Files menu doesn't close previous editor state
If you have a file open with the editor, and you go to the files menu and create a new file, the editor remains open with the old code in it.

https://user-images.githubusercontent.com/1316441/235541936-dfc921cd-94c8-4755-b6f7-f5c1131a87a4.mp4

This same problem exists if you create a new file from the command palette.

### PR DESCRIPTION
**Pull request by jimniels**
Fixes #462 

Note: there are currently 3 different places that can create a new file:

1. Quadratic menu (File -> New)
2. Command palette
3. File menu (File -> Open -> Create file)

No. 2 & 3 suffer from this bug where if the code editor is open when you create a new file it doesn't disappear when the new file is opened.

### CODE REVIEW

File: src/ui/menus/FileMenu/FileMenu.tsx [hunk 1]
```diff
@@ -66,10 +66,10 @@ export function FileMenu(props: FileMenuProps) {
       app.reset();
     }
 
-    setEditorInteractionState({
-      ...editorInteractionState,
+    setEditorInteractionState((prevState) => ({
+      ...prevState,
       showFileMenu: false,
-    });
+    }));
```
Comment (jimniels) [inline src/ui/menus/FileMenu/FileMenu.tsx:72]: Was simply stale state 🤦‍♂️

File: src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx [hunk 2]
```diff
@@ -67,9 +67,9 @@ export const QuadraticMenu = (props: Props) => {
         <MenuDivider />
         <SubMenu label="File">
           <MenuItem
-            onClick={() => {
+            onClick={async () => {
+              await createNewFile();
```
Comment (jimniels) [inline src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx:71]: Make this the same order as the others: create the new file, then reset the sheet.

File: src/hooks/useGenerateLocalFiles.tsx [hunk 3]
```diff
@@ -83,6 +84,8 @@ export const useGenerateLocalFiles = (sheetController: SheetController): LocalFi
       sheetController.clear();
       sheetController.sheet.load_file(grid);
       sheetController.app?.rebuild();
+      sheetController.app?.reset();
+      focusGrid();
```
Comment (jimniels) [inline src/hooks/useGenerateLocalFiles.tsx:88]: Rather than call `app.reset()` everywhere we call `createNewFile`, this now runs the reset inside the function itself, so consumers of `createNewFile` only need to call it.

File: src/ui/menus/CodeEditor/CodeEditor.tsx [hunk 4]
```diff
@@ -134,9 +134,11 @@ export const CodeEditor = (props: CodeEditorProps) => {
...
 
   useEffect(() => {
-    // focus editor on show editor change
-    editorRef.current?.focus();
-    editorRef.current?.setPosition({ lineNumber: 0, column: 0 });
+    if (editorInteractionState.showCodeEditor) {
+      // focus editor on show editor change
+      editorRef.current?.focus();
+      editorRef.current?.setPosition({ lineNumber: 0, column: 0 });
+    }
```
Comment (jimniels) [inline src/ui/menus/CodeEditor/CodeEditor.tsx:141]: We don't need to set the focus on the editor if it's not visible.

**Comment by jimniels** [comment]
This is fixed, however it is worth noting the follow minor bugs that still remain:

1. If you enter a cell value for `0,0` in the code editor (say `1+1`), then create a new file, then leave the cursor at `0,0` and go to edit the cell, the old value from the previous sheet (`1+1`) will still be there (if you move the cursor once you've created the new sheet, it won't)
2. If you have unsaved changes in the code editor, and create a new file, those changes will be _discarded_ with no prompt to save them. This issue is in the app today and beyond the scope of this PR.

**Review by davidkircos — APPROVED** [review]
