### PR TITLE
Fix blank grid loading on mobile

### LINKED ISSUE #815: bug: When loading files on mobile they appear blank until moving the viewport
Tested on `main` / iPhone / Chrome

### PR DESCRIPTION
**Pull request by davidkircos**
Fixes #815

When loading documents on mobile, they previously show up blank until moving the viewport.

### CODE REVIEW

File: src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx [hunk 1]
```diff
@@ -51,6 +52,7 @@ export const QuadraticMenu = () => {
   useEffect(() => {
     if (isMobile) {
```
Comment (davidkircos) [inline src/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx:53]: For mobile, Headers are set to not visible by default. For some reason this resulted in a partial render of the grid by default for all files loaded on mobile.

**Review by davidfig — APPROVED** [review]
