### PR TITLE
show file extension in import error message for unsupported type

### LINKED ISSUE #813: bug: Import non .grid files fails ungracefully
Users have been trying to import Excel files, via the import button the dashboard. I am not sure if windows enforces the file extension request in the code.

Request to check the file extension after upload and provide feedback on exactly what file types are supported. Only .grid.

CleanShot 2023-11-14 at 22 37 25@2x

CleanShot 2023-11-15 at 11 52 57@2x

### PR DESCRIPTION
**Pull request by davidkircos**
fixes #813

previously
CleanShot 2024-06-20 at 15 09 30@2x

now 
CleanShot 2024-06-20 at 15 09 49@2x

### CODE REVIEW

File: quadratic-client/src/app/helpers/files.ts [hunk 1]
```diff
@@ -23,26 +23,29 @@ export function stripExtension(name: string): string {
   return name.replace(/\.[^/.]+$/, '');
 }
 
-export function has_extension(name: string, extension: string): boolean {
+export function getExtension(name: string): string {
```
Comment (ddimaria) [inline quadratic-client/src/app/helpers/files.ts:26]: Ha, I think this was me, too much switching between Rust and TS.

**Review by ddimaria — APPROVED** [review]
