### PR TITLE
fix: show sql error

### LINKED ISSUE #1705: bug: Sql cells don't show ERROR when they are in the ERROR state
CleanShot 2024-08-12 at 11 42 59@2x

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1705

### CODE REVIEW

**Review by davidkircos — APPROVED** [review]
Functionality looks good! Waiting on code review

File: quadratic-core/src/controller/execution/control_transaction.rs [hunk 1]
```diff
@@ -2,21 +2,16 @@ use chrono::Utc;
...
-        transaction::Transaction,
-        transaction_summary::{CELL_SHEET_HEIGHT, CELL_SHEET_WIDTH},
-        transaction_types::JsCodeResult,
-    },
-    error_core::Result,
-    grid::{CodeRun, CodeRunResult},
-    parquet::parquet_to_vec,
-    Pos, Value,
-};
+use crate::controller::active_transactions::pending_transaction::PendingTransaction;
```
Comment (ddimaria) [inline quadratic-core/src/controller/execution/control_transaction.rs:5]: Was this copilot, or do you just prefer an import style?

Comment (ddimaria) [reply quadratic-core/src/controller/execution/control_transaction.rs:5]: We should agree on a consistent format as a team to avoid these hard-to-read diffs.

**Review by ddimaria — APPROVED** [review]

File: quadratic-core/src/controller/execution/control_transaction.rs (hunk 1 above)
Comment (AyushAgrawal-A2) [reply quadratic-core/src/controller/execution/control_transaction.rs:5]: I update rust toolchain to nightly and since then linting is different... these happen automatically on save

Comment (ddimaria) [reply quadratic-core/src/controller/execution/control_transaction.rs:5]: @AyushAgrawal-A2 I don't think we want to be on nightly.  Was there a specific reason for it?

Comment (AyushAgrawal-A2) [reply quadratic-core/src/controller/execution/control_transaction.rs:5]: @ddimaria I was trying bulk memory and rust concurrency in wasm
toolchain is local but it messed up my linting style
