### PR TITLE
fix: rendering issues with formatting

### LINKED ISSUE #2717: Rendering issues with formatting
## Describe the bug
Sheets with lots of formatting eventually break.

Msg Luke for repro - very tricky. 

## Reproduction
Msg Luke, lots of activity to repro 

General repro is add tons of formatting to a sheet with some data and eventually column resizes will break.

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## Relevant issue(s)
closes #2717

### CODE REVIEW

**Review by luke-quadratic — CHANGES_REQUESTED** [review]
see slack feedback - change does not fix

**Review by luke-quadratic — CHANGES_REQUESTED** [review]
Issue persists

**Review by luke-quadratic — APPROVED** [review]
Latest change works, hooray!

File: quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts [hunk 1]
```diff
@@ -123,7 +123,6 @@ class RenderCore {
   ): Promise<JsRenderCell[]> => {
     return new Promise((resolve, reject) => {
       if (!this.renderCorePort) {
-        console.warn('Expected renderCorePort to be defined in RenderCore.getRenderCells');
```
Comment (ddimaria) [inline quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts:126]: Is this no longer important to warn?

Comment (AyushAgrawal-A2) [reply quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts]: it is, removed by mistake

**Review by ddimaria — APPROVED** [review]
