### PR TITLE
fix: pasting formula text doesn't automatically create formula

### LINKED ISSUE #1757: Pasting formula text doesn't automatically create formula
Should automatically create the result for the pasted formula 

CleanShot 2024-08-22 at 11 23 36

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1757

### CODE REVIEW

File: quadratic-core/src/controller/operations/cell_value.rs [hunk 1]
```diff
@@ -247,6 +253,47 @@ mod test {
         );
     }
 
+    #[test]
```
Comment (davidfig) [inline quadratic-core/src/controller/operations/cell_value.rs:256]: :heart:

**Review by davidfig — APPROVED** [review]

**Comment by luke-quadratic** [comment]
n1 - works on functionality

**Review by davidkircos — APPROVED** [review]
