### PR TITLE
fix: JS charts after refresh

### LINKED ISSUE #1703: Charts broken after refresh
- [ ] JS
- [X] Python

CleanShot 2024-08-12 at 10 12 39@2x

To recreate: 
1. Create charts in ~~either Python or~~ JS 
2. Refresh 
3. Charts mia

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1703 

fixes: importing grid v1_5 file with js chart, Javascript intro example

### CODE REVIEW

**Review by luke-quadratic — APPROVED** [review]
works as intended!

File: quadratic-core/src/grid/file/v1_5/file.rs [hunk 1]
```diff
@@ -284,6 +285,10 @@ fn upgrade_code_runs(sheet: &v1_5::Sheet) -> Vec<(v1_6::Pos, v1_6::CodeRun)> {
                                         v1_6::OutputValue::Single(v1_6::CellValue::Html(
                                             value.value.to_owned(),
                                         ))
+                                    } else if value.type_field.to_lowercase() == "image" {
```
Comment (ddimaria) [inline quadratic-core/src/grid/file/v1_5/file.rs:288]: I feel like I saw this added before 🤔

File: quadratic-rust-shared/data/grid/upgrade_code_runs_v1_5.grid [hunk 2]
```diff
@@ -1 +1 @@
...
...ror":false,"last_modified":1722896901}],[{"x":0,"y":4},{"formatted_code_string":null,"std_out":null,"std_err":null,"cells_accessed":[],"result":{"size":{"w":1,"h":1},"values":[{"type":"html","value":""}]},"return_type":null,"line_number":null,"output_type":null,"spill_error":false,"last_modified":1722896906}],[{"x":1,"y":4},{"formatted_code_string":null,"std_out":null,"std_err":null,"cells_accessed":[],"result":{"size":{"w":2,"h":1},"values":[{"type":"html","value":""},{"type":"html","value":""}]},"return_type":null,"line_number":null,"output_type":null,"spill_error":false,"last_modified":1722896901}],[{"x":0,"y":5},{"formatted_code_string":null,"std_out":null,"std_err":null,"cells_accessed":[],"result":{"size":{"w":1,"h":1},"values":[{"type":"image","value":""}]},"return_type":null,"line_number":null,"output_type":null,"spill_error":false,"last_modified":1722896906}],[{"x":1,"y":5},{"formatted_code_string":null,"std_out":null,"std_err":null,"cells_accessed":[],"result":{"size":{"w":2,"h":1},"values":[{"type":"image","value":""},{"type":"image","value":""}]},"return_type":null,"line_number":null,"output_type":null,"spill_error":false,"last_modified":1722896901}]]}],"version":"1.5"}
```
Comment (ddimaria) [inline quadratic-rust-shared/data/grid/upgrade_code_runs_v1_5.grid:1]: What changed in this file?  Since we're on v1.6, changes to these older files indicate the schema changed (or not?).

**Review by ddimaria — APPROVED** [review]
Looks good, I just have a schema change question.

File: quadratic-core/src/grid/file/v1_5/file.rs (hunk 1 above)
Comment (AyushAgrawal-A2) [reply quadratic-core/src/grid/file/v1_5/file.rs:288]: @ddimaria 
yup, in last fix https://github.com/quadratichq/quadratic/pull/1643 I added a other missing types fields, didn't know about image type then

File: quadratic-rust-shared/data/grid/upgrade_code_runs_v1_5.grid (hunk 2 above)
Comment (ddimaria) [reply quadratic-rust-shared/data/grid/upgrade_code_runs_v1_5.grid:1]: I think I follow: this enum variant existed in v1.5, we just were not testing it?

Comment (AyushAgrawal-A2) [reply quadratic-rust-shared/data/grid/upgrade_code_runs_v1_5.grid:1]: @ddimaria 
correct, this files tests import of coderun type fields from v1.5 to v1.6... image type is now added to import as well as test
