### PR TITLE
Fix blank string cells from copy/paste/import csv

### LINKED ISSUE #818: feat: Strip Whitespace on Paste/CSV Import
- leading and trailing whitespace when importing data
- if this results in an empty string for a cell, keep the cell blank

### PR DESCRIPTION
**Pull request by davidkircos**
fixes #818

### CODE REVIEW

File: quadratic-core/src/controller/cells.rs [hunk 1]
```diff
@@ -36,13 +36,16 @@ impl GridController {
         &mut self,
         sheet_id: SheetId,
         pos: Pos,
-        value: &str,
+        raw_value: &str,
```
Comment (ddimaria) [inline quadratic-core/src/controller/cells.rs:39]: Shadowing is OK in Rust, so you don't have to change this name.  It's a complete 180 degree shift from JS.  You'd just need to update line 47: 
```rust
let value = value.trim();
```

**Review by ddimaria — APPROVED** [review]
Easy to review this one!  I have one comment, but it's not important just a note.

File: quadratic-core/src/controller/cells.rs (hunk 1 above)
Comment (davidkircos) [reply quadratic-core/src/controller/cells.rs]: nice!

**Review by davidfig — APPROVED** [review]
