### PR TITLE
fix: auto row resize on setting format wrap in data tables

### LINKED ISSUE #2368: bug: wrapping a cell doesn't increase row size
When clicking the Wrap button, it should show all of my data by increasing the row size
https://app.arcade.software/share/fDZ55UtketxB7DVPm2nD

Luke edit: seems this might be just a thing if name is hidden on a code cell/table

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## Relevant issue(s)
closes #2368

### CODE REVIEW

**Review by cole-at-quadratic — APPROVED** [review]

**Review by luke-quadratic — APPROVED** [review]
This was an important fix and works as expected, thanks. 

Tested: only tested wrapping behavior

File: quadratic-core/src/controller/execution/auto_resize_row_heights.rs [hunk 1]
```diff
@@ -767,4 +768,123 @@ mod tests {
         let async_transaction = gc.transactions.get_async_transaction(next_transaction.id);
         assert!(async_transaction.is_err());
     }
+
+    #[test]
+    fn test_table_rows_resize_on_cell_wrap() {
```
Comment (ddimaria) [inline quadratic-core/src/controller/execution/auto_resize_row_heights.rs:773]: 💯

File: quadratic-core/src/grid/data_table/send_render.rs [hunk 2]
```diff
@@ -68,6 +65,48 @@ impl DataTable {
...
+        include_blanks: bool,
+    ) -> Vec<i64> {
+        let mut rows = vec![];
+        let formats_x_offset = data_table_pos.x - 1;
+        let formats_y_offset = data_table_pos.y - 1 + self.y_adjustment(true);
+        for y in rect.y_range() {
+            for x in rect.x_range() {
+                if (include_blanks
+                    || self
+                        .cell_value_at((x - data_table_pos.x) as u32, (y - data_table_pos.y) as u32)
```
Comment (ddimaria) [inline quadratic-core/src/grid/data_table/send_render.rs:94]: Not sure I have any advice, but this isn't quick to scan.

File: quadratic-core/src/grid/data_table/send_render.rs [hunk 3]
```diff
@@ -77,56 +116,55 @@ impl DataTable {
...
-                .to_rects_with_rect_bounds(data_table_rect)
+                .to_rects_with_rect_bounds(data_table_formats_rect)
                 .for_each(|(x1, y1, x2, y2, _)| {
-                    let mut rect = Rect::new(x1, y1, x2, y2);
-                    // translate to actual data table pos
-                    rect.translate(data_table_pos.x - 1, data_table_pos.y - 1);
-                    // add y adjustment to factor in table name and headers
-                    rect.max.y += self.y_adjustment(true);
-                    dirty_hashes.extend(rect.to_hashes());
+                    let formats_rect = Rect::new(x1, y1, x2, y2);
```
Comment (ddimaria) [inline quadratic-core/src/grid/data_table/send_render.rs:124]: This code is duplicated in `wrap_transaction_changes()`, consider combining into a separate function.

**Review by ddimaria — APPROVED** [review]
Code looks good, though you might want to have @davidfig look at the render code.

File: quadratic-core/src/grid/data_table/send_render.rs (hunk 2 above)
Comment (AyushAgrawal-A2) [reply quadratic-core/src/grid/data_table/send_render.rs:94]: I have split out the check to make it slightly more readable

File: quadratic-core/src/grid/data_table/send_render.rs (hunk 3 above)
Comment (AyushAgrawal-A2) [reply quadratic-core/src/grid/data_table/send_render.rs:126]: There are some difference making it hard to combine these two, want to keep it separate

**Review by davidfig — APPROVED** [review]
