### PR TITLE
fix: dark mode issues

### LINKED ISSUE #2006: bug: dark mode issues
- [ ] rename file - can't read in dark mode, has white background
- [ ] grid text - click into a cell in dark mode, text is also dark and can't read until clicking out of that particular cell

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #2006

### CODE REVIEW

**Review by jimniels — APPROVED** [review]
LGTM 👍 

(I increased the contrast for the selection too, as it was _really_ dark in dark mode — still not optimal, but an improvement)

File: quadratic-client/src/app/ui/loading/QuadraticLoading.tsx [hunk 1]
```diff
@@ -25,6 +25,7 @@ export function QuadraticLoading() {
   return (
     <>
       {/* ToBarLoading allows window to be moved while loading in electron */}
+      <ThemeAppearanceModeEffects />
```
Comment (jimniels) [inline quadratic-client/src/app/ui/loading/QuadraticLoading.tsx:28]: What does this fix? [This component is already mounted in the root-most component](https://github.com/quadratichq/quadratic/blob/qa/quadratic-client/src/routes/_root.tsx#L36), so this would be mounting it twice?

Comment (jimniels) [reply quadratic-client/src/app/ui/loading/QuadraticLoading.tsx:28]: Idk if it's related, but per [David's comment](https://github.com/quadratichq/quadratic/issues/2006#issuecomment-2465284171), it does seem like [the TopBarLoading component has a hard-coded background color value](https://github.com/quadratichq/quadratic/blob/qa/quadratic-client/src/app/ui/components/TopBarLoading.tsx#L10) which we should get rid of and just add `bg-background` class

Comment (AyushAgrawal-A2) [reply quadratic-client/src/app/ui/loading/QuadraticLoading.tsx:28]: QuadraticLoading is also a route fallback, 

When the app opens, we see QuadraticLoading twice, once as route fallback and another time when app is syncing offline / multiplayer transactions. I was seeing the first loading screen as white and 2nd one as black.

This effect is contained inside QuadraticLoading, which is a temporary, it will not conflict / execute twice with the other effect

Comment (AyushAgrawal-A2) [reply quadratic-client/src/app/ui/loading/QuadraticLoading.tsx:28]: Regarding the topbar, it is an extra component, I added dark-mode-hack to that as well.
I am not sure why this component exists or is it even need now.

Comment (jimniels) [reply quadratic-client/src/app/ui/loading/QuadraticLoading.tsx:28]: Yeah it was because there was an electron app at one point but there hasn't been in a looooooong time. AFAIK that's the only reason that component exists

**Review by jimniels — APPROVED** [review]

File: quadratic-client/src/app/ui/loading/QuadraticLoading.tsx (hunk 1 above)
Comment (davidkircos) [reply quadratic-client/src/app/ui/loading/QuadraticLoading.tsx:28]: Jim is right that is why it was created^

**Review by davidkircos — APPROVED** [review]
