### PR TITLE
fix: rendering of multiplayer transactions

### LINKED ISSUE #2623: Multiplayer Chunks Disappear
## Describe the bug
When two or more users are editing a document, and a multiplayer user edits a chunk not visible to you, then you scroll back to it it will disappear. When editing something in that chunk it reappears.

NOTE: CAN RECREATE CHUNKS DISAPPEARING OUTSIDE OF MULTIPLAYER AS WELL

Image

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## Relevant issue(s)
closes #2623

## Description
there are side effects (mostly rendering) on transaction which happen in `finalize_transaction`, these were not happening correctly for multiplayer transactions
now `finalize_transaction` is called for all transactions (mp, rollback, reapply, etc)

### CODE REVIEW

**Review by luke-quadratic — APPROVED** [review]
I cranked extremely hard trying to get rendering issues to reappear on this in multiplayer and couldn't recreate in this branch.

File: quadratic-client/src/app/atoms/editorInteractionStateAtom.ts [hunk 1]
```diff
@@ -59,6 +60,68 @@ export const editorInteractionStateAtom = atom<EditorInteractionState>({
...
+      };
+      events.on('transactionStart', handleTransactionStart);
+
+      const handleTransactionEnd = (transaction: TransactionInfo) => {
+        setSelf((prev) => {
+          if (prev instanceof DefaultValue) return prev;
+
+          return {
+            ...prev,
+            transactionsInfo: [...prev.transactionsInfo.filter((t) => t.transactionId !== transaction.transactionId)],
```
Comment (ddimaria) [inline quadratic-client/src/app/atoms/editorInteractionStateAtom.ts:85]: Some duplication here, could abstract into a separate fn.

File: quadratic-client/src/app/atoms/editorInteractionStateAtom.ts [hunk 2]
```diff
@@ -59,6 +60,68 @@ export const editorInteractionStateAtom = atom<EditorInteractionState>({
...
+      return () => {
+        events.off('transactionStart', handleTransactionStart);
+        events.off('transactionEnd', handleTransactionEnd);
+      };
+    },
+    // this effect is used to focus the grid when the modal is closed
+    ({ onSet }) => {
+      onSet((newValue, oldValue) => {
+        if (oldValue instanceof DefaultValue) return;
+        const oldModalShow =
```
Comment (ddimaria) [inline quadratic-client/src/app/atoms/editorInteractionStateAtom.ts:100]: The logic duplication can be abstracted as well.

File: quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts [hunk 3]
```diff
@@ -199,7 +199,7 @@ export class CellsTextHash {
           );
           this.renderCellsReceivedTime = performance.now();
         } catch (e) {
-          this.dirty = true;
+          this.dirty = dirty;
```
Comment (ddimaria) [inline quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts:202]: Nice catch!

File: quadratic-core/src/controller/active_transactions/pending_transaction.rs [hunk 4]
```diff
@@ -178,10 +178,7 @@ impl PendingTransaction {
 
     /// Sends the transaction to the multiplayer server (if needed)
     pub fn send_transaction(&self) {
-        if self.complete
-            && self.is_user_undo_redo()
-            && (cfg!(target_family = "wasm") || cfg!(test))
-            && !self.is_server()
+        if self.complete && self.is_user_undo_redo() && (cfg!(target_family = "wasm") || cfg!(test))
```
Comment (ddimaria) [inline quadratic-core/src/controller/active_transactions/pending_transaction.rs:181]: Consider moving wasm detection to the new api file once merged.

**Review by ddimaria — APPROVED** [review]
Looks good, some nits to consider.

File: quadratic-client/src/app/atoms/editorInteractionStateAtom.ts (hunk 1 above)
Comment (AyushAgrawal-A2) [reply quadratic-client/src/app/atoms/editorInteractionStateAtom.ts]: done

File: quadratic-client/src/app/atoms/editorInteractionStateAtom.ts (hunk 2 above)
Comment (AyushAgrawal-A2) [reply quadratic-client/src/app/atoms/editorInteractionStateAtom.ts:96]: done

File: quadratic-core/src/controller/active_transactions/pending_transaction.rs (hunk 4 above)
Comment (AyushAgrawal-A2) [reply quadratic-core/src/controller/active_transactions/pending_transaction.rs:181]: will do
