### PR TITLE
fix: spill outlines not drawing

### LINKED ISSUE #3234: Spill outlines not drawing
## Describe the bug
Spill outlines not drawing 

## Reproduction

https://github.com/user-attachments/assets/009c6319-6e75-4c09-b8fa-2d97286b01be

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## Relevant issue(s)
closes #3234

### CODE REVIEW

**Review by luke-quadratic — APPROVED** [review]
Fix works

File: quadratic-core/src/grid/sheet/data_tables/cache.rs [hunk 1]
```diff
@@ -134,6 +134,21 @@ impl SheetDataTablesCache {
         }
         false
     }
+
+    pub fn tables_in_range(&self, range: RefRangeBounds) -> impl Iterator<Item = Pos> {
```
Comment (ddimaria) [inline quadratic-core/src/grid/sheet/data_tables/cache.rs:138]: Add a test for this?

File: quadratic-core/src/grid/contiguous/contiguous_2d.rs [hunk 2]
```diff
@@ -190,7 +190,15 @@ impl<T: Default + Clone + PartialEq + fmt::Debug> Contiguous2D<T> {
 
     /// Returns a list of rectangles containing non-default values.
     pub fn nondefault_rects_in_rect(&self, rect: Rect) -> impl Iterator<Item = (Rect, T)> {
-        let [x1, x2, y1, y2] = range_to_rect(RefRangeBounds::new_relative_rect(rect));
+        self.nondefault_rects_in_range(RefRangeBounds::new_relative_rect(rect))
+    }
+
+    /// Returns a list of rectangles containing non-default values.
+    pub fn nondefault_rects_in_range(
```
Comment (ddimaria) [inline quadratic-core/src/grid/contiguous/contiguous_2d.rs:197]: Add a test for this?

**Review by ddimaria — APPROVED** [review]
Code looks good, but some tests could be added.
