### PR TITLE
fix: focus grid after closing GoTo menu and CellType menu

### LINKED ISSUE #1592: Opening and closing command palette doesn't return focus to the sheet
To recreate: 
- open command palette with / 
- close command palette
- try to do a formula with = or open command palette again with /, won't be possible

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1592

### CODE REVIEW

**Comment by davidkircos** [comment]
Do you know where the underlying issue is? Why does adding a delay work?

**Comment by AyushAgrawal-A2** [comment]
> Do you know where the underlying issue is? Why does adding a delay work?

Actually only `setTimeout(() => focusGrid());` also works for me, delay value is not required
Reason for
- setTimeout -> call `focusGrid` after state update and react re-render
- 100ms delay -> I saw this being used in other places for `focusGrid` and I assumed it may be required for other browsers. I am just testing on chrome. Firefox and safari can be finicky.

File: quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx [hunk 1]
```diff
@@ -98,7 +98,7 @@ export default function CellTypeMenu() {
       ...editorInteractionState,
       showCellTypeMenu: false,
     });
-    focusGrid();
+    setTimeout(() => focusGrid(), 100);
```
Comment (ddimaria) [inline quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx:101]: Is there an event to listen to in order to avoid possible timing issues with the current approach @AyushAgrawal-A2?

Comment (AyushAgrawal-A2) [reply quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx:101]: The correct approach to do this in React should be using useEffect + useRef 
I think it can be achieved using recoil atom effects as well. I'll give it a try.

**Comment by AyushAgrawal-A2** [comment]
@ddimaria 
I have switched to recoil atom effects
