### PR TITLE
fix: table name update on duplicate sheet

### LINKED ISSUE #2336: Sheet duplication table + code bug
- Duplication of a sheet that has a table and a reference to that table: the code reference should stay the same in the original sheet; in the new sheet it should reference the newly created table 

Current behavior: original sheet is getting its reference edited, new sheet has strange ref instead of just new table ref

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #2336

### CODE REVIEW

File: quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs [hunk 1]
```diff
@@ -46,26 +50,53 @@ impl GridController {
...
+                        context.table_map.insert(table_map_entry);
+                    }
+
+                    data_tables_pos.push(*pos);
+                    table_names_to_update_in_cell_ref.push((old_name, unique_name));
+
                     transaction.add_code_cell(sheet_id, *pos);
                 }
 
-                self.send_add_sheet(transaction, sheet_id);
```
Comment (davidfig) [inline quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs:67]: Is the sheet info sent automatically?

**Review by davidfig — APPROVED** [review]

**Review by davidkircos — APPROVED** [review]
functionality looks good to me, fixes both bugs gabe reported with sheet duplicate

File: quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs [hunk 2]
```diff
@@ -46,35 +49,62 @@ impl GridController {
...
+
+                // update table names in data tables in the new sheet
+                let sheet = self.try_sheet_mut_result(sheet_id)?;
+                for (pos, data_table) in sheet.data_tables.iter_mut() {
+                    let old_name = data_table.name.to_string();
+                    let unique_name = unique_data_table_name(&old_name, false, None, &context);
+                    data_table.name = unique_name.to_owned().into();
+
+                    // update table context for replacing table names in code cells
+                    if let Some(mut table_map_entry) = context.table_map.remove(&old_name) {
```
Comment (ddimaria) [inline quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs:69]: This may be a good fn to add to context for reuse.

**Review by ddimaria — APPROVED** [review]

**Review by luke-quadratic — APPROVED** [review]
