### PR TITLE
fix: double-click to inline edit scrolls the sheet incorrectly

### LINKED ISSUE #1770: bug: double-click to inline edit scrolls the sheet incorrectly
Step to reproduce:
- Scroll down in a sheet.
- Double click a cell to edit.
- Sheet scroll and this cell is out of view.
- On scrolling back, same cell is in editing mode.

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1770

### CODE REVIEW

**Comment by davidfig** [comment]
How do you show the cell when out of view?

File: quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts [hunk 1]
```diff
@@ -95,6 +95,7 @@ class InlineEditorMonaco {
     if (!this.editor) {
       throw new Error('Expected editor to be defined in focus');
     }
+    inlineEditorHandler.keepCursorVisible();
```
Comment (AyushAgrawal-A2) [inline quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts:98]: @davidfig 
keep cursor visible is called here,
focus is already being called in atom effects.
when we focus inline editor, we also want it to be visible, so made sense to me to just add it here

**Review by davidfig — APPROVED** [review]

**Review by davidkircos — APPROVED** [review]
