### PR TITLE
fix: rendering bugs due to viewport_core pr

### LINKED ISSUE #1867: Formatting and alignment not working in QA
Blocking on QA
CleanShot 2024-09-13 at 16 02 52

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #1867

### CODE REVIEW

File: quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts [hunk 1]
```diff
@@ -141,15 +141,15 @@ class RenderCore {
       };
       this.renderCorePort.postMessage(message);
       this.waitingForResponse.set(id, (cells: JsRenderCell[]) => {
-        clearTimeout(timeOut);
+        // clearTimeout(timeOut);
```
Comment (davidfig) [inline quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts:144]: delete these?

**Review by davidfig — APPROVED** [review]
