### PR TITLE
fix: AddDataTable and GridToDataTable op

### LINKED ISSUE #2454: Data disappearing on table creation followed by undo
To recreate: 
1. paste in some data
2. turn into a table 
3. undo 
4. data missing (note that the missing cell is also broken, can't be edited, etc.)
Image

Redo also fails to work.

https://github.com/user-attachments/assets/5771f597-c5be-44b8-be21-0a63fb7db61d

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## Relevant issue(s)
closes #2454
fixes https://github.com/quadratichq/quadratic/pull/2427#issuecomment-2712040005

## Description
Fixes AddDataTable op - rendering and undo

## (Optional) Any extra testing considerations?
No

## (Optional) Any dependent docs, links, etc.?
No

### CODE REVIEW

**Review by ddimaria — APPROVED** [review]

**Comment by ddimaria** [comment]
@AyushAgrawal-A2 I think we lost some coverage on this one.  Could you add a test for this scenario or add on to the existing test for this?

**Comment by AyushAgrawal-A2** [comment]
> @AyushAgrawal-A2 I think we lost some coverage on this one. Could you add a test for this scenario or add on to the existing test for this?

done

**Comment by luke-quadratic** [comment]
Seeing same issue in this branch 
CleanShot 2025-03-11 at 15 30 20

**Comment by AyushAgrawal-A2** [comment]
> Seeing same issue in this branch

@luke-quadratic 
fixed

**Review by luke-quadratic — APPROVED** [review]
awesome, solves both issues

File: quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs [hunk 1]
```diff
@@ -152,15 +152,32 @@ impl GridController {
             // select the entire data table
             Self::select_full_data_table(transaction, sheet_id, data_table_pos, &data_table);
 
-            sheet.set_cell_value(data_table_pos, cell_value);
-            sheet.data_tables.insert_sorted(data_table_pos, data_table);
+            let old_value = sheet.set_cell_value(data_table_pos, cell_value);
+            let old_data_table = sheet.data_tables.insert_sorted(data_table_pos, data_table);
```
Comment (ddimaria) [inline quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs:156]: Nit: it might be more expressive to destructure this: 
```rust
let (index, data_table) = sheet.data_tables.insert_sorted(data_table_pos, data_table);
```

File: quadratic-core/src/controller/user_actions/data_table.rs [hunk 2]
```diff
@@ -464,13 +473,85 @@ mod tests {
...
         }
 
         gc.redo(None);
         {
             let sheet = gc.sheet(sheet_id);
+            assert!(sheet.cell_value(pos![D1]).is_some());
             assert!(sheet.data_table(pos![D1]).is_some());
         }
+
+        // overwrite second data table with a new data table
```
Comment (ddimaria) [inline quadratic-core/src/controller/user_actions/data_table.rs:490]: Great tests 💯

**Review by ddimaria — APPROVED** [review]
Approved, with an optional nit and a question

File: quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs (hunk 1 above)
Comment (AyushAgrawal-A2) [reply quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs:156]: done

File: quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs [hunk 3]
```diff
@@ -587,15 +604,15 @@ impl GridController {
...
-                },
                 Operation::SetCellFormatsA1 {
                     sheet_id,
                     formats: sheet_format_update,
                 },
+                Operation::SetCellValues {
+                    sheet_pos,
+                    values: old_values.into(),
+                },
+                Operation::DeleteDataTable { sheet_pos },
```
[the remark this answers is not in the document]
Comment (AyushAgrawal-A2) [reply quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs:615]: `Operation::DeleteDataTable` deletes both value and the table, `finalize_data_table` is not called or required here

image

**Comment by davidfig** [comment]
Works great.

**Review by davidkircos — APPROVED** [review]
nice, looks good to me
