### PR TITLE
fix: drag and drop AI Chat image/pdf indicator persists

### LINKED ISSUE #2901: Drag and drop AI Chat image/pdf indicator persists
## Describe the bug

If you drag over the widget but don't finish dropping into it it will persists permanently and can only be cleared with refresh. 

## Reproduction

Drag your file over and out of the chat 

https://github.com/user-attachments/assets/7246062a-2f6c-4d49-8827-5ed0283f47f2

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## Relevant issue(s)
closes #2901

### CODE REVIEW

File: quadratic-client/src/app/ui/components/AIUserMessageForm.tsx [hunk 1]
```diff
@@ -195,7 +195,7 @@ export const AIUserMessageForm = memo(
     );
 
     const handleDrag = useCallback(
-      (e: DragEvent<HTMLFormElement | HTMLDivElement>) => {
+      (e: DragEvent<HTMLFormElement | HTMLDivElement> | DragEvent<HTMLTextAreaElement>) => {
```
Comment (ddimaria) [inline quadratic-client/src/app/ui/components/AIUserMessageForm.tsx:198]: Could you do:
```ts
(e: DragEvent<HTMLFormElement | HTMLDivElement | HTMLTextAreaElement>
```

File: quadratic-client/src/app/ui/components/AIUserMessageForm.tsx [hunk 2]
```diff
@@ -281,6 +279,7 @@ export const AIUserMessageForm = memo(
           autoHeight={true}
           maxHeight={maxHeight}
           disabled={waitingOnMessageIndex !== undefined}
+          onDragEnter={handleDrag}
```
Comment (ddimaria) [inline quadratic-client/src/app/ui/components/AIUserMessageForm.tsx:282]: What about `onDragOver`?

**Review by luke-quadratic — APPROVED** [review]
Works
