### PR TITLE
Fix command palette column/row inserts 

### LINKED ISSUE #2638: Insert/delete row & column from command palette doesn't work
## Describe the bug
Insert/delete row & column from command palette doesn't work 

## Expected behavior
Should mirror menu behaviors

### PR DESCRIPTION
**Pull request by luke-quadratic**
## Relevant issue(s)
Resolves #2638 

Based on user report from yday (easier to just resolve than scope/assign/add to the end of the list)

### CODE REVIEW

File: quadratic-client/src/app/ui/menus/CommandPalette/commands/ColumnRow.tsx [hunk 1]
```diff
@@ -19,7 +20,16 @@ const columnRowCommandGroup: CommandGroup = {
         );
       },
     },
+    Action.InsertColumnLeft,
+    Action.InsertColumnRight,
+    Action.DeleteColumn,
```
Comment (AyushAgrawal-A2) [inline quadratic-client/src/app/ui/menus/CommandPalette/commands/ColumnRow.tsx:25]: we should not mix command objects with actions here

File: quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx [hunk 2]
```diff
@@ -114,20 +115,24 @@ export const CommandPalette = () => {
...
+                        // @ts-expect-error - Some actions expect args but can run without them
+                        actionSpec.run();
+                      } else {
+                        // @ts-expect-error - Pass empty object as args if args are required
+                        actionSpec.run({});
+                      }
+                    }}
                     icon={'Icon' in actionSpec && actionSpec.Icon ? <actionSpec.Icon /> : null}
-                    shortcut={keyboardShortcutEnumToDisplay(commandOrAction)}
+                    shortcut={keyboardShortcutEnumToDisplay(commandOrAction as Action)}
```
Comment (AyushAgrawal-A2) [inline quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx:135]: we should not type cast here but check type and call functions accordingly
type casting should not be necessary and will be very brittle

**Review by AyushAgrawal-A2 — CHANGES_REQUESTED** [review]

File: quadratic-client/src/app/ui/menus/CommandPalette/commands/ColumnRow.tsx (hunk 1 above)
Comment (AyushAgrawal-A2) [reply quadratic-client/src/app/ui/menus/CommandPalette/commands/ColumnRow.tsx:25]: done

**Review by davidfig — APPROVED** [review]

**Review by AyushAgrawal-A2 — APPROVED** [review]
