### PR TITLE
fix bug with numeric decimals

### LINKED ISSUE #1477: Can't reduce precision when entire column or row is selected
See gif 

Image

### PR DESCRIPTION
**Pull request by davidfig**
Fixes bug with numeric decimal size when using columns and rows

Fixes #1477

### CODE REVIEW

File: quadratic-core/src/grid/sheet.rs [hunk 1]
```diff
@@ -329,7 +319,7 @@ impl Sheet {
     /// get or calculate decimal places for a cell
     pub fn decimal_places(&self, pos: Pos, is_percentage: bool) -> Option<i16> {
         // first check if numeric_decimals already exists for this cell
-        if let Some(decimals) = self.get_column(pos.x)?.numeric_decimals.get(pos.y) {
+        if let Some(decimals) = self.format_cell(pos.x, pos.y, true).numeric_decimals {
```
Comment (ddimaria) [inline quadratic-core/src/grid/sheet.rs:322]: This seems less efficient than before.  Do you need to get all of the formats for the column before accessing the numeric decimals?

**Comment by luke-quadratic** [comment]
Works on columns but not rows

File: quadratic-core/src/grid/sheet.rs (hunk 1 above)
Comment (davidfig) [reply quadratic-core/src/grid/sheet.rs:322]: You're right. I fixed it. It'll be fine once we move to an all-in format style for cells.

**Review by davidkircos — APPROVED** [review]
