### PR TITLE
fix: swap out more icon componentry related to MUI

### LINKED ISSUE #2858: bug: connection logos in goto menu are wrong
## Describe the bug
Connections aren't displaying properly in the goto menu

Image

## Expected behavior

Those should display as a Postgres logo (as they're postgres connections)

### PR DESCRIPTION
**Pull request by jimniels**
## Description

- Fixes #2858
- Swaps out more of our custom icons for ones in material design (where possible)
- Removes our dependence on MUI components for custom icons related to languages (e.g. python, sql, etc).
- Language icons take on their brand colors (rather than 1-color, see python for example) and are a standard size/appearance throughout the app now.

See inline comments for previews of changes. Example:

Before:

After:

### CODE REVIEW

File: quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx [hunk 1]
```diff
@@ -152,7 +152,7 @@ export const CodeEditorHeader = ({ editorInst }: CodeEditorHeaderProps) => {
       >
         <TooltipPopover label={`${codeCell?.label}${unsavedChanges ? ' · Unsaved changes' : ''}`} side="bottom">
           <div className="flex items-center">
-            <LanguageIcon language={codeCell?.id} fontSize="small" />
+            <LanguageIcon language={codeCell?.id} />
```
Comment (jimniels) [inline quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx:155]: CleanShot 2025-05-01 at 11 55 35@2x

File: quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx [hunk 2]
```diff
@@ -191,7 +191,7 @@ export const GoTo = ({ tableInfo }: { tableInfo: JsTableInfo[] }) => {
                 onSelect={() => selectTable(name)}
                 name={name}
                 nameSecondary={tableNameToRange(name)}
-                icon={<LanguageIcon language={getLanguage(language)} sx={{ width: 16, height: 16 }} />}
+                icon={<LanguageIcon language={getConnectionKind(language)} />}
```
Comment (jimniels) [inline quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx:194]: CleanShot 2025-05-01 at 11 55 52@2x

File: quadratic-client/src/dashboard/components/NewFileButton.tsx [hunk 3]
```diff
@@ -106,7 +106,9 @@ export default function NewFileButton({ isPrivate }: { isPrivate: boolean }) {
               return (
                 <DropdownMenuItem key={uuid} asChild>
                   <Link to={to} reloadDocument>
-                    <LanguageIcon language={type} className="mr-3" />
+                    <div className="mr-3">
+                      <LanguageIcon language={type} />
+                    </div>
```
Comment (jimniels) [inline quadratic-client/src/dashboard/components/NewFileButton.tsx:111]: CleanShot 2025-05-01 at 11 56 19@2x

File: quadratic-client/src/dashboard/components/OnboardingBanner.tsx [hunk 4]
```diff
@@ -1,9 +1,9 @@
-import { LanguageIcon } from '@/app/ui/components/LanguageIcon';
 import { useFileImport } from '@/app/ui/hooks/useFileImport';
 import Logo from '@/dashboard/components/quadratic-logo.svg';
 import { useDashboardRouteLoaderData } from '@/routes/_dashboard';
 import type { TeamAction } from '@/routes/teams.$teamUuid';
 import { apiClient } from '@/shared/api/apiClient';
+import { LanguageIcon } from '@/shared/components/LanguageIcon';
```
Comment (jimniels) [inline quadratic-client/src/dashboard/components/OnboardingBanner.tsx:6]: Moved this component to the top-most level of the app in `shared` since it's not only used in the app. It's used on the dashboard too

Comment (jimniels) [reply quadratic-client/src/dashboard/components/OnboardingBanner.tsx:6]: CleanShot 2025-05-01 at 11 58 20@2x

File: quadratic-client/src/shared/components/Icons.tsx [hunk 5]
```diff
@@ -682,3 +682,15 @@ export const ArrowDownIcon: IconComponent = (props) => {
...
+  return <Icon {...props}>step_out</Icon>;
+};
+
+export const SheetGoToIcon: IconComponent = (props) => {
+  return <Icon {...props}>step_into</Icon>;
+};
+
+export const GenericLanguageIcon: IconComponent = (props) => {
+  return <Icon {...props}>subject</Icon>;
+};
```
Comment (jimniels) [inline quadratic-client/src/shared/components/Icons.tsx:696]: Using icons from our material set (rather than the old ones that were hard coded).

What it looks like now:

CleanShot 2025-04-30 at 12 37 52@2x

File: quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx [hunk 6]
```diff
@@ -40,7 +40,7 @@ export const ConnectionSchemaBrowser = ({
         <div className="flex items-center gap-1 truncate">
           {data && data.type ? (
             <div className="flex h-6 w-6 flex-shrink-0 items-center">
-              <LanguageIcon language={data.type} sx={{ width: 15, height: 15 }} />
+              <LanguageIcon language={data.type} />
```
Comment (jimniels) [inline quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx:43]: CleanShot 2025-05-01 at 12 01 01@2x

File: quadratic-client/src/shared/components/connections/ConnectionsList.tsx [hunk 7]
```diff
@@ -141,7 +141,7 @@ function ListItems({
             )}
           >
             <div className="flex h-6 w-6 items-center justify-center">
-              <LanguageIcon language={type} fontSize="small" />
+              <LanguageIcon language={type} />
```
Comment (jimniels) [inline quadratic-client/src/shared/components/connections/ConnectionsList.tsx:144]: CleanShot 2025-05-01 at 12 01 21@2x

File: quadratic-client/src/shared/components/LanguageIcon.tsx [hunk 8]
```diff
@@ -0,0 +1,172 @@
...
+          fill="#00758F"
+        />
+      </g>
+      <defs>
+        <clipPath id="clip0_904_46">
+          <rect width="20" height="20" fill="white" />
+        </clipPath>
+      </defs>
+    </svg>
+  );
```
[the remark this answers is not in the document]
Comment (jimniels) [reply quadratic-client/src/shared/components/LanguageIcon.tsx:115]: yeah this is expected as it cuts off what overflows (because this dolphin is really small otherwise)

**Review by luke-quadratic — APPROVED** [review]
Awesome 

Tested: 
- Looked around in every nook and cranny to try to find a broken icon, couldn't find any 
- Created a connection, logo appeared correctly 
- Language icons look sweet

**Review by ddimaria — APPROVED** [review]
