### PR TITLE
Fix Match formula

### LINKED ISSUE #1916: Match formula not working
Not sure cause, but replicating in other sheets returns results correctly. 

See sheet in Slack for recreation.

### PR DESCRIPTION
**Pull request by HactarCE**
Fixes #1916

### CODE REVIEW

File: quadratic-core/src/formulas/functions/lookup.rs [hunk 1]
```diff
@@ -461,21 +461,24 @@ fn lookup<V: ToString + AsRef<CellValue>>(
...
+                    LookupSearchMode::LinearReverse => {
+                        lookup_regex(regex, haystack.iter().rev()).map(fix_rev_index)
+                    }
+                    LookupSearchMode::BinaryAscending | LookupSearchMode::BinaryDescending => {
+                        internal_error!(
+                            "invalid match_mode+search_mode combination \
+                             should have been caught earlier in XLOOKUP",
+                        );
+                    }
+                });
```
Comment (HactarCE) [inline quadratic-core/src/formulas/functions/lookup.rs:478]: This block is unchanged, just indented

**Review by ddimaria — APPROVED** [review]

**Comment by HactarCE** [comment]
The lines lacking coverage are internal errors that should be unreachable. It's just a bugfix + regression test, so no user test required. Merging now.
