### PR TITLE
fix: clicking sheet references across sheets doesn't get saved

### LINKED ISSUE #2639: Clicking sheet references across sheets doesn't get saved
## Describe the bug
If you click a reference from another sheet in a Formula that sheet does not populate the Formula. 

Note in video how cross-sheet reference doesn't populate. 

Image

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
## Relevant issue(s)
closes #2639

### CODE REVIEW

**Review by luke-quadratic — APPROVED** [review]
Works as expected

File: quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts [hunk 1]
```diff
@@ -75,12 +75,11 @@ export class CellHighlights extends Container {
...
-    cellsAccessed
-      .filter(({ sheetId }) => sheetId === sheets.current)
-      .flatMap(({ ranges }) => ranges)
-      .forEach((range, index) => {
-        if (selectedCellIndex === undefined || selectedCellIndex !== index || !inlineEditorHandler.cursorIsMoving) {
+    this.cellsAccessed.forEach(({ sheetId, ranges }, index) => {
+      if (sheetId !== sheets.current) return;
+
+      ranges.forEach((range) => {
+        if (selectedCellIndex !== index || !inlineEditorHandler.cursorIsMoving) {
```
Comment (ddimaria) [inline quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts:82]: nit: could be a filter applied to the forEach()

**Review by ddimaria — APPROVED** [review]
