### PR TITLE
fix: a1 bug, references overrunning their bounds

### LINKED ISSUE #2161: A1 bug: references overrunning their bounds
CleanShot 2025-01-06 at 13 16 40@2x

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #2161

### CODE REVIEW

File: quadratic-core/src/controller/execution/run_code/run_formula.rs [hunk 1]
```diff
@@ -18,34 +18,30 @@ impl GridController {
...
+                    result: CodeRunResult::Ok(output.inner),
+                    return_type: None,
+                    line_number: None,
+                    output_type: None,
+                };
+                transaction.cells_accessed.clear();
+                self.finalize_code_run(transaction, sheet_pos, Some(new_code_run), None);
+            }
+            Err(error) => {
+                let _ = self.code_cell_sheet_error(transaction, &error);
```
Comment (ddimaria) [inline quadratic-core/src/controller/execution/run_code/run_formula.rs:44]: Is this hiding of the error intentional?  I know this was in the previous code.

**Review by ddimaria — APPROVED** [review]
The code looks good.  I asked @davidfig to take a quick peek since it deals with bounds.

**Review by davidfig — APPROVED** [review]

**Review by luke-quadratic — APPROVED** [review]
great
