### PR TITLE
fix: copy-paste a code cell isn't changing relative reference if sheet name is included

### LINKED ISSUE #2171: Copy-paste a code cell isn't changing relative reference if sheet name is included
CleanShot 2025-01-07 at 18 04 39

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
closes #2171

### CODE REVIEW

**Comment by luke-quadratic** [comment]
Works great

File: quadratic-core/src/grid/code_cell.rs [hunk 1]
```diff
@@ -37,22 +43,18 @@ impl CodeCellValue {
...
-                let start_quote = &caps[1]; // The quote type used at the start
-                let cell_ref_str = &caps[2]; // Capture the first argument inside quotes
-                let end_quote = &caps[3]; // The quote type used at the end
+                let a1_str = &caps[2]; // Capture the first argument which is inside quotes
 
-                // if the quotes are mismatched, return the original string
-                if start_quote != end_quote {
-                    return full_match.to_string();
-                }
+                dbg!(&a1_str);
```
Comment (davidfig) [inline quadratic-core/src/grid/code_cell.rs:50]: remove

**Review by davidfig — APPROVED** [review]

File: quadratic-core/src/grid/code_cell.rs (hunk 1 above)
Comment (AyushAgrawal-A2) [reply quadratic-core/src/grid/code_cell.rs:50]: done

File: quadratic-core/src/a1/a1_selection/mod.rs [hunk 2]
```diff
@@ -632,6 +635,14 @@ mod tests {
         );
     }
 
+    #[test]
+    fn test_invalid_sheet_name() {
+        assert_eq!(
+            A1Selection::from_str("Sheet' 1'!A1", &SheetId::test(), &HashMap::new()),
+            Err(A1Error::InvalidSheetName("Sheet' 1'!A1".to_string())),
```
Comment (ddimaria) [inline quadratic-core/src/a1/a1_selection/mod.rs:642]: 🙌

**Review by ddimaria — APPROVED** [review]
Looks good.  We should evaluate some of these crates since cloudfront doesn't brotli 
compress files over 10MB (our release build is at 11MB before this addition)
